language: yongning-na_04
#title: Yongning-na Transcription Character Inventory
data_roots:
  - ~/projects/my-projects/asr-models/language-downloads/yongning-na_01/doreco_yong1270_core_v2.0/
report_dir: ../reports/yongning-na
report_name: "{language}_data_inventory.md"
transcription_globs:
#   - "*.txt"
   - "*.eaf"
#   - "*.TextGrid"
#   - "*.csv"
csv_text_column: form
textgrid_tier: segments
eaf_tier: W-0
example_limit: 3
context_chars: 24


# Chao numbers may contain any number of levels. Chao letter contours are discovered as maximal runs made from the five primitive letters below. Additionally, these are the following is only to override what is already present in the inventory (line 25)
# Defaults are: chao_number_regex: "[1-5]{2}"; chao_letters: ["˥", "˦", "˧", "˨", "˩"]; diacritic_markers: ["◌̀", "◌́", "◌̂", "◌̃", "◌̄", "◌̆", "◌̈", "◌̊", "◌̌", "◌̩", "◌̯"]
chao_number_regex: "[1-5]{1,}"
chao_letters:
  - "˥"
  - "˦"
  - "˧"
  - "˨"
  - "˩"
diacritic_markers:
  - "◌̀"
  - "◌́"
  - "◌̂"
  - "◌̃"
  - "◌̄"
  - "◌̆"
  - "◌̈"
  - "◌̊"
  - "◌̌"
  - "◌̩"
  - "◌̯"
